Develop 🔀 master
pontuslaestadius/carpet pull request #8
Opened 2018-03-16 10:55 UTC by pontuslaestadius

2018-03-19 08:13 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +          --push	  pushes the to the docker hub of the next argument user id.
So this is a two argument command?

2018-03-19 08:34 UTC, lainqvrnstrm commented on chain.sh
> +						# clean up with prompt, only works with bash and often not user shell.
Could be worth mentioning in the README?

2018-03-19 10:42 UTC, pontuslaestadius commented
Travis says this does not work? why

2018-03-19 12:06 UTC, lainqvrnstrm requested changes

2018-03-19 12:06 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +-b        --build         builds using the default Dockerfile in current directory.
Preferably, add "an image", so we know what it is building.

2018-03-20 10:59 UTC, lainqvrnstrm requested changes

2018-03-20 10:59 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +          --push	  pushes the to the docker hub of the next argument user id.
"requested access to the resource is denied", is that what we want?

2018-03-20 10:59 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +	  --debug	  runs in debug mode using valgrind.
Doesn't work without the build directory, which you recommend to remove above.

2018-03-20 10:59 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +	  --debug	  runs in debug mode using valgrind.
Does work after having used the --local flag and the project has been built.

2018-03-20 10:59 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +-d        --delete        deletes the toolchain container.
"Error: No such container: carpet_compile"

2018-03-20 10:59 UTC, lainqvrnstrm commented on chain.sh
> +	--run)
--run flag does not exist in the .CHAIN_HELP file

2018-03-20 10:59 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +-f        --force         deletes ignores warnings and removes previous container.
is used with --run

2018-03-20 10:59 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +-d        --delete        deletes the toolchain container.
Have to run "bash chain.sh --run" first.

2018-03-20 10:59 UTC, lainqvrnstrm commented on .CHAIN_HELP
> +-d        --delete        deletes the toolchain container.
Should it still be called the toolchain container?

2018-03-28 12:20 UTC, lainqvrnstrm approved these changes

2018-03-28 12:21 UTC, merged